###
POST http://localhost:8080/api/v1/client
Content-Type: application/json

{
  "email": "asdad.2020@smu.edu.sg",
  "isAdmin": true
}

###
PUT http://localhost:8080/api/v1/client/{{ac2380ca-7fd3-47e5-9f51-f22000bd2e14}}
Content-Type: application/json

{
  "email": "linashen@gmail.com",
  "isAdmin": false
}


